# Generated by Django 6.0 on 2025-12-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='keywords',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=500, verbose_name='Ключевые слова'),
        ),
    ]
